### ISSUE TITLE
support for REFEDS hide-from-discovery category

### ISSUE THREAD

**Issue by peter-** [andreassolberg/DiscoJuice#51]
Entities carrying the `http://macedir.org/entity-category` entity attibute with the  `http://refeds.org/category/hide-from-discovery` attribute value should not be shown in discojuice.
(At least not unless some other UI element is added to allow subjects to also see any hidden entities, which would probably add too much noise to the UI.)

**Comment by andreassolberg** [comment]
I'm implementing this now in <https://github.com/andreassolberg/DiscoJuice-Backend> which will be the backend replacing the current (and old) DiscoJuice backend.
